# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
substitutions:
    _IMAGE_VERSION: 1.0.0
  steps:
    - id: "Versão go"
      name: "gcr.io/cloud-builders/go"
      args: ["version"]
      env: ["GOPATH=."]

    - id: "Rodando teste"
      name: "gcr.io/cloud-builders/go"
      args: ["test","./..."]
      env: ["GOPATH=."]

    - id: 'Rodando build'
      name: 'gcr.io/cloud-builders/docker'
      args:
        - 'build'
        - '-t'
        - 'gcr.io/$PROJECT_ID/soma-go:latest'
        - '-t'
        - 'gcr.io/$PROJECT_ID/soma-go:${_IMAGE_VERSION}'
        - '-f'
        - '.docker/Dockerfile'
        - '--target'
        - 'prod'
        - '.'
  
  images:
    - 'gcr.io/$PROJECT_ID/soma-go:latest'
    - 'gcr.io/$PROJECT_ID/soma-go:${_IMAGE_VERSION}'